package com.freightscaler.bid.consumer;

import com.freightscaler.bid.model.Bid;
import com.freightscaler.bid.model.BidEvent;
import com.freightscaler.bid.model.BidStatus;
import com.freightscaler.bid.repository.BidRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.time.Instant;

/**
 * Kafka consumer that processes bid events sequentially per loadId (partition key).
 * This is the write side of the write-flattening pattern:
 * HTTP → Kafka → sequential consumer → DB insert.
 */
@Component
public class BidEventConsumer {

    private static final Logger log = LoggerFactory.getLogger(BidEventConsumer.class);

    private final BidRepository bidRepository;

    public BidEventConsumer(BidRepository bidRepository) {
        this.bidRepository = bidRepository;
    }

    @KafkaListener(topics = "${bid.topic:bid-events}", groupId = "bid-svc")
    public void onBidEvent(BidEvent event) {
        if (!"SUBMITTED".equals(event.type())) {
            log.debug("Ignoring non-SUBMITTED event type={} for load={}", event.type(), event.loadId());
            return;
        }

        Instant start = Instant.now();

        Bid bid = new Bid(
                null, // generated by DB
                event.loadId(),
                event.carrierId(),
                event.rateCents(),
                null, // estimatedHours not carried in event for simplicity
                false, // riskAck not carried in event
                BidStatus.SUBMITTED,
                event.occurredAt()
        );

        Bid inserted = bidRepository.insert(bid);

        Duration latency = Duration.between(event.occurredAt(), Instant.now());
        log.info("Processed bid: bidId={} loadId={} carrier={} latency={}ms",
                inserted.id(), inserted.loadId(), inserted.carrierId(), latency.toMillis());
    }
}
