FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY app "${LAMBDA_TASK_ROOT}/app"

USER 10001

CMD ["app.lambda_handler.handler"]
